name: CLI Build Test

on:
  push:
    branches: [ cli-test ]
  pull_request:
    branches: [ cli-test ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libavformat-dev libavfilter-dev libavdevice-dev ffmpeg libasound2-dev tesseract-ocr libtesseract-dev
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test --release

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Setup Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.1
    - name: Install Visual Studio components
      run: |
        choco install visualstudio2022buildtools -y
        choco install visualstudio2022-workload-vctools -y
        choco install cmake -y
    - name: Install additional tools
      run: |
        choco install pkgconfiglite -y
    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat -disableMetrics
        .\vcpkg.exe integrate install --disable-metrics
        .\vcpkg.exe install ffmpeg
    - name: Set environment variables
      run: |
        echo "PKG_CONFIG_PATH=$env:GITHUB_WORKSPACE\vcpkg\packages\ffmpeg_x64-windows\lib\pkgconfig" >> $env:GITHUB_ENV
        echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" >> $env:GITHUB_ENV
        echo "LIBCLANG_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin" >> $env:GITHUB_ENV
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test --release
