name: Windows Integration Test

on:
  push:
    branches: [ cli-test ]
  pull_request:
    branches: [ cli-test ]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install dependencies
      shell: pwsh
      run: |
        choco install ffmpeg tesseract imagemagick
        echo "C:\Program Files\Tesseract-OCR" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Verify installations
      shell: pwsh
      run: |
        ffmpeg -version
        tesseract --version
        magick -version

    - name: Build CLI
      run: cargo build --release

    - name: Debug environment
      shell: pwsh
      run: |
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "User profile: $env:USERPROFILE"
        Get-WmiObject -Class Win32_VideoController | Select-Object Name, AdapterRAM, DriverVersion
        Write-Host "PATH: $env:PATH"

    - name: Prepare OCR test image
      shell: pwsh
      run: |
        magick -size 300x100 xc:white -font Arial -pointsize 24 -fill black -draw "text 10,50 'Hello, Screenpipe OCR'" test_image.png

    - name: Prepare audio test file
      shell: pwsh
      run: |
        Add-Type -AssemblyName System.Speech
        $synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
        $synth.SetOutputToWaveFile("test_audio.wav")
        $synth.Speak("This is a test for Screenpipe audio capture")
        $synth.Dispose()

    - name: Run CLI and capture output
      shell: pwsh
      run: |
        $env:PATH += ";C:\Program Files\Tesseract-OCR;C:\ProgramData\chocolatey\bin"
        $process = Start-Process -FilePath ".\target\release\screenpipe.exe" -ArgumentList "--debug" -PassThru -RedirectStandardOutput "screenpipe_output.log" -RedirectStandardError "screenpipe_error.log" -NoNewWindow
        Start-Sleep -Seconds 10
        
        # Display OCR test image
        Start-Process -FilePath "mspaint.exe" -ArgumentList "test_image.png" -PassThru
        Start-Sleep -Seconds 20
        
        # Play audio test file
        (New-Object Media.SoundPlayer "test_audio.wav").PlaySync()
        Start-Sleep -Seconds 30
        
        Stop-Process -Id $process.Id -Force

    - name: Check for crashes and expected behavior
      shell: pwsh
      run: |
        Write-Host "Checking for log file..."
        $LogFile = Get-ChildItem -Path $env:USERPROFILE -Recurse -Filter "screenpipe.log" -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
        if ($LogFile) {
          Write-Host "Log file found at: $LogFile"
          if (Select-String -Path $LogFile -Pattern "panic" -Quiet) {
            Write-Host "CLI crashed"
            Get-Content $LogFile
            exit 1
          }
          Write-Host "CLI ran successfully without crashing"
          Get-Content $LogFile -Tail 50
          
          # Check for OCR result
          if (Select-String -Path $LogFile -Pattern "Hello, Screenpipe OCR" -Quiet) {
            Write-Host "OCR test passed: Text was recognized"
          } else {
            Write-Host "OCR test failed: Text was not recognized"
            exit 1
          }
          
          # Check for audio capture result
          if (Select-String -Path $LogFile -Pattern "test for Screenpipe audio capture" -Quiet) {
            Write-Host "Audio capture test passed: Text was transcribed"
          } else {
            Write-Host "Audio capture test failed: Text was not transcribed"
            exit 1
          }
        } else {
          Write-Host "Log file not found, checking standard output..."
          Get-Content "screenpipe_output.log" -Tail 50
          Get-Content "screenpipe_error.log" -Tail 50
          exit 1
        }

    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenpipe-logs
        path: |
          ${{ env.USERPROFILE }}\.screenpipe\logs\
          screenpipe_output.log
          screenpipe_error.log

    - name: Upload captured data
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenpipe-data
        path: ${{ env.USERPROFILE }}\.screenpipe\data\

    - name: Upload test files
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-files
        path: |
          test_image.png
          test_audio.wav